spring.application.name=expense-splitter

spring.datasource.url=jdbc:mysql://localhost:3306/expense_db

spring.datasource.username=expense_user
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

